--liquibase formatted sql

--changeset dizhak:1
CREATE TABLE IF NOT EXISTS public.download_result
(
    id                      bigint generated by default as identity
        primary key,
    task_uuid               uuid          not null,
    download_url            varchar(1024) not null,
    http_method             varchar(8),
    request_headers         varchar(2048),
    request_cookies         varchar(1024),
    proxy_host              varchar(1024),
    proxy_port              integer,
    proxy_username          varchar(255),
    proxy_password          varchar(255),
    download_text           varchar(10485760),
    download_status         integer,
    download_status_message varchar(16),
    response_content_type   varchar(128),
    response_headers        varchar(2048),
    response_cookies        varchar(1024),
    response_timestamp      timestamp(6),
    attempt_count           integer,
    created_at              timestamp(6) with time zone,
    modified_at             timestamp(6) with time zone,
    created_by              varchar(255),
    last_modified_by        varchar(255)
);
--rollback DROP TABLE public.download_result


-- --changeset dizhak:2
-- alter table public.download_result
--     owner to postgres;

